### ISSUE TITLE
Design issues

### ISSUE THREAD

**Issue by Halama** [keboola/keboola-academy#7]
Jak to vypadá teď tak to ne zcela sedí s designem, např. ty texty nejsou oproti sobě vycentrovaný a jsou jinak velký.

### Návrh
https://projects.invisionapp.com/share/7CGOEIYDPW3#/screens/289165992_keboola_Academy_4

![image](https://user-images.githubusercontent.com/903531/38921056-14800ff8-42f5-11e8-8386-24da790828be.png)

### Realita:)

![image](https://user-images.githubusercontent.com/903531/38921106-32191aaa-42f5-11e8-9df1-9f00175041de.png)

**Comment by janmichek** [comment]
- upravil jsem styly a pridal zakladni responzivitu na par radku.
- ten form je ted zkracenej schvalne, oproti visualni predloze? vytratil se tam to tiz ten efekt nalejvni do hlavy xD
- potreboval bych teda jeste re-publishnout ty fonty, Zmenil jsem tam rezy fontu. ale me to nejde. -viz screen. Asi tu udelas znovu rucne, jak jsi psal? https://github.com/keboola/keboola-academy/pull/5
@Halama 



![image](https://user-images.githubusercontent.com/15363559/38933583-b3223694-4319-11e8-90e7-69ffc26f29b5.png)

![image](https://user-images.githubusercontent.com/15363559/38933600-bedbb3fc-4319-11e8-9de8-bc00454f1cbc.png)

![image](https://user-images.githubusercontent.com/15363559/38933699-0511e2a6-431a-11e8-9863-639aa3077631.png)

**Comment by Halama** [comment]
na ten form přímo bych se zatím vyprdnul at na tom nepálíme čas, celé je to dost minor věc.
Vypadá to dobře podle screenu. Ty fonty tam jdu nahodit.

**Comment by Halama** [comment]
Je to nasazený na https://preview.keboola.academy/ @jancermak hoď na to prosím oko. 
dík

**Comment by jancermak** [comment]
@janmichek  — mam jednu vec — a to na mobilu dat to keboola academy na jeden radek http://take.ms/KiOkt

**Comment by janmichek** [comment]
@jancermak Diky za podnet, nerad bych do toho zabrusoval, ale  zalezi na konkretnim devicu. U me by se to neveslo na jednu radku. Bylo by potrebovat udelat pokrocilejsi responsivitu, a to prozatim nema cenu.

**Comment by ujovlado** [comment]
Nefixlo by sa to jednoduchou zmenou markupu? Teraz je to tam nejako divne cez h1, h2, h3 ...

**Comment by janmichek** [comment]
@ujovlado Nerozumim kam tim miris? Hele me je to jedno, rad se s tim vyhraju. Mam za to, ze je to okrajova vec - viz https://github.com/keboola/keboola-academy/issues/7#issuecomment-382388630
